# remote_theme: pages-themes/slate@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

# title: "Clearer Views for Cancer Research: Upgrading Chromosome Analysis"
# description: "UC San Diego, Halıcıoğlu Data Science Institute"

header_pages:
  - about.md
  - portfolio.md

gem "minima"
$ bundle

# header_pages:
#   - about.md
#   - portfolio.md
