title: "Capstone"
theme: minima

# gem 'jekyll-titles-from-headings'
plugins:
  - jekyll-titles-from-headings
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 

header_pages:
  - about.md
  - Github.md
  - Report.md
